---
title: "About us"
---

This reading group is founded by two Concordia graduate students, Veronique and Soroosh. By uniting two very different fields of study, we wished to broaden the scope of our understanding of the ethical, social and scientific aspects of AI and to complement each other&#39;s expertise on the subject.

- Veronique is currently doing a MA in social and cultural anthropology at Concordia. Her interests are varied and include artificial intelligence, medical anthropology, food sovereignty, and indigenous studies.
- Soroosh is pursuing his Ph.D. in the field of artificial intelligence, with emphasis on biomedical and health-related problems. His research interests fall under the umbrella of "AI for Good", and he is curious about Ethical AI from a mathematical and algorithmic point of view.

**We would love to have anyone who is interested in this topic on board!**

**You do not have to be a computer scientist to join in (although it&#39;s definitely awesome if you&#39;re one!).**

**We believe every field of study has great insights to bring into this subject and could bring an important contribution to this reading group!**

<!-- We are a group of students at Concordia University, Montreal, Canada, who are interested in studying the field of **Artificial Intelligence (AI)**from a transdisciplinary point of view. We want to know what are the effects of AI on our **society** and how can we integrate **ethical** ways of thinking in AI-based services. What should **computer-scientists** know and what should **policy makers** know? What is our **responsibility** towards AI? Shall we consider AI as **citizens** of our society and shall we treat them with the same set of **regulations** that we already have or should we rethink the concepts of **consciousness**, **humanity** and **self-awareness**? -->

<!-- *We are going to read and read and read to **solidify our thoughts** for each of the above questions.* -->

<!-- This reading group is founded by two Concordia students, Veronique and Soroosh, and we would love to have anyone who is interested in this topic on board. Veronique is studying anthropology and Soroosh is student in computer science.  -->



