---
title: "Our Events"
---

Here, we keep track of our future and previous events, so that you can plan for upcoming events. 


### Next meeting:  
Friday, April 24th, 5 pm  
Topic: Confirmation bias and algorithms  
Join on [Zoom](https://concordia-ca.zoom.us/j/91300135925?pwd=eDhkZllOeXlBcjFtM3FQeFhzdmFUQT09)  
*password to join the meeting will be shared on Slack channel*

**How to contribute:**  

- choose a reading scheduled for this week from the [suggested readings list](https://docs.google.com/spreadsheets/d/1-4fWa2iJq3akLqBrp7KlOlEz5ewvzFwQc0fsGp0aUuQ/edit)

- add your name in the "volunteer" column next to the reading you chose

- read the text and prepare yourself to present it to others in the reading group

- you can prepare a reflection piece (summary) for the group using this [template](https://docs.google.com/document/d/1Ctv7_TUgpbCmrBiDnxUHzhES2m4E1jd9EzuUcIUC4-A/edit)

- you will have 15 minutes to present your reading to the group

- be prepared to answer questions on the reading you did

- enjoy the other members' presentations and take part in the discussion!


